trigger:
  branches:
    include:
      - master
variables: []
pool:
  vmImage: ubuntu-latest
steps:
  - script: |-
      # Download build.sh
      curl $BEDROCK_BUILD_SCRIPT > build.sh
      chmod +x ./build.sh
    displayName: Download bedrock bash scripts
    env:
      BEDROCK_BUILD_SCRIPT: $(BUILD_SCRIPT_URL)
  - script: |-
      # From https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/release.sh
      . build.sh --source-only

      # Initialization
      verify_access_token
      init
      helm init

      # Fabrikate
      get_fab_version
      download_fab

      # SPK
      get_spk_version
      download_spk

      # Clone HLD repo
      git_connect

      # Update HLD via spk
      git checkout -b "RECONCILE/$(Build.Repository.Name)-$(Build.BuildNumber)"
      echo "spk hld reconcile $(Build.Repository.Name) $PWD ./.."
      spk hld reconcile $(Build.Repository.Name) $PWD ./..
      echo "GIT STATUS"
      git status
      echo "GIT ADD (git add -A)"
      git add -A

      # Set git identity
      git config user.email "admin@azuredevops.com"
      git config user.name "Automated Account"

      # Commit changes
      echo "GIT COMMIT"
      git commit -m "Reconciling HLD with $(Build.Repository.Name)-$(Build.BuildNumber)."

      # Git Push
      git_push

      # Open PR via az repo cli
      echo 'az extension add --name azure-devops'
      az extension add --name azure-devops

      echo 'az repos pr create --description "Reconciling HLD with $(Build.Repository.Name)-$(Build.BuildNumber)."'
      az repos pr create --description "Reconciling HLD with $(Build.Repository.Name)-$(Build.BuildNumber)."
    displayName: "Download Fabrikate and SPK, Update HLD, Push changes, Open PR"
    env:
      ACCESS_TOKEN_SECRET: $(PAT)
      AZURE_DEVOPS_EXT_PAT: $(PAT)
      REPO: $(HLD_REPO)
