stages:
- stage: setup
  jobs:
  - job: "download_spk_artifact"
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: 'ca459769-cfe0-490c-a89e-1f1eb2eba550'
        definition: '20'
        buildVersionToDownload: 'latestFromBranch'
        branchName: 'refs/heads/master'
        artifactName: 'spk_linux_node_12'
        targetPath: '$(Pipeline.Workspace)'
    - script: |
        ls -ld '$(Pipeline.Workspace)'
        cd $(Pipeline.Workspace)
        #alias spk=${pwd}/spk-linux
        pwd
        spk-linux --version
    displayName: "ECHO DIR"
