stages:
- stage: setup
  jobs:
  - job: "download_spk_artifact"
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: 'ca459769-cfe0-490c-a89e-1f1eb2eba550'
        definition: '20'
        buildVersionToDownload: 'latestFromBranch'
        branchName: 'refs/heads/master'
        itemPattern: "spk*"
        artifactName: 'spk_linux_node_12'
        targetPath: '$(System.DefaultWorkingDirectory)'
    - script: |
        shopt -s expand_aliases
        echo "Current Dir is $(pwd)"
        ls -l
        chmod +x spk-linux
        ls -l
        alias spk="$(pwd)/spk-linux"
        spk --version
      displayName: "ECHO DIR"
    - script: |
        alias spk="$(pwd)/spk-linux"
        export PLAYGROUND_DIR="$(System.DefaultWorkingDirectory)/playground"
        echo "Running from $(pwd)"

        if [ -d "$PLAYGROUND_DIR"  ]; then rm -Rf $PLAYGROUND_DIR; fi

        if [ ! -d "$PLAYGROUND_DIR" ]; then
          echo "PLAYGROUND_DIR does not exist"
          mkdir $PLAYGROUND_DIR
          echo "PLAYGROUND_DIR created"
        fi
        cd $PLAYGROUND_DIR
        spk --version
      displayName: "CREATING DIR"

