# Default values for sample-helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: fabrikam
  tag: stable
  pullPolicy: Always

serviceName: "service"

service:
  port: 80
