# Azure CLI Specific Configuration
azure_cli:
  version: "2.0.70"
  Extensions:
    aks_preview: "0.4.14"

# Azure DevOps Configuration
azure_devops: # Should this live under the `spk` configuration?
  org: "my-az-do-org"
  project: "my-mono-repo-project"
  hld_repository: "my-hld-repository"
  manifest_repository: "my-manifest-repository"
  access_token: "access-token" # This is your Personal Access Token with permission to modify and access this private repo. Ex. "${env:AZDO_PERSONAL_ACCESS_TOKEN}". Leave this empty if project is public

infra:
  terraform: "v0.12.6"
  helm: "v2.14.3"
  git: "2.17.1"
  bedrock: # If you would like to use a forked or custom version of bedrock
    # Releases are through tags / branches
    source: "https://github.com/microsoft/bedrock.git"
    tag:
    access_token: "" # This is your Personal Access Token with permission to modify and access this private repo. Ex. "${env:BEDROCK_PERSONAL_ACCESS_TOKEN}". Leave this empty if project is public

introspection:
  azure: # This is the storage account for the service introspection tool
    account_name: "${env:test_name}"
    table_name: "table-name"
    partition_key: "partition-key"
    key: "${env:test_key}"
    # Following is needed if using spk to onboard to use introspection tool
    service_principal_id: "service-principal-id"
    service_principal_secret: "service-principal-secret"
    subscription_id: "subscription-id"
    tenant_id: "tenant-id"
