name: Node CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install az cli
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: yarn install, lint, build, and test
        run: |
          yarn
          yarn lint
          yarn build
          yarn test
        env:
          CI: true
